version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: todo-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - todo-app-mysql-data:/var/lib/mysql
    networks:
      - todo-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: todo-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: todoapp
      DB_USER: todo_user
      DB_PASSWORD: user_password
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge

volumes:
  todo-app-mysql-data:
    driver: local
