// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/todos": {
            "get": {
                "description": "Bu endpoint, tüm todo'ları listeler.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Get all Todos",
                "responses": {
                    "200": {
                        "description": "Todo'lar başarıyla listelendi",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ent.Todo"
                            }
                        }
                    },
                    "500": {
                        "description": "Todo'lar listelenemedi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Bu endpoint, yeni bir todo eklemek için kullanılır.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Create a new Todo",
                "parameters": [
                    {
                        "description": "Todo nesnesi",
                        "name": "todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ent.Todo"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Todo başarıyla eklendi",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Geçersiz veri",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Todo eklenemedi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/todos/{id}": {
            "get": {
                "description": "Bu endpoint, belirli bir todo'yu getirir.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Get a Todo by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Belirli todo başarıyla getirildi",
                        "schema": {
                            "$ref": "#/definitions/ent.Todo"
                        }
                    },
                    "400": {
                        "description": "Geçersiz ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Todo bulunamadı",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Veritabanı hatası",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Bu endpoint, belirli bir todo'yu günceller.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Update a Todo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Todo nesnesi",
                        "name": "todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ent.Todo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Todo başarıyla güncellendi",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Geçersiz veri",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Todo güncellenemedi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Bu endpoint, belirli bir todo'yu siler.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "Delete a Todo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Todo başarıyla silindi",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Geçersiz ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Todo silinemedi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Bu endpoint, kullanıcı adı ve şifre ile giriş yapmayı sağlar.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kullanıcı"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Kullanıcı Giriş Bilgileri",
                        "name": "loginUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                },
                                "username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Başarıyla giriş yapıldı",
                        "schema": {
                            "$ref": "#/definitions/ent.User"
                        }
                    },
                    "401": {
                        "description": "Yetkilendirme başarısız",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Sunucu hatası",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ent.Todo": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description holds the value of the \"description\" field.",
                    "type": "string"
                },
                "id": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "title": {
                    "description": "Title holds the value of the \"title\" field.",
                    "type": "string"
                }
            }
        },
        "ent.User": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "password": {
                    "description": "Password holds the value of the \"password\" field.",
                    "type": "string"
                },
                "role": {
                    "description": "Role holds the value of the \"role\" field.",
                    "type": "string"
                },
                "username": {
                    "description": "Username holds the value of the \"username\" field.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Todo App API",
	Description:      "This is a simple Todo App API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
