basePath: /
definitions:
  todos.Todo:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple Todo App API.
  title: Todo App API
  version: "1.0"
paths:
  /todos:
    get:
      description: Bu endpoint tüm todo'ları listeler.
      produces:
      - application/json
      responses:
        "200":
          description: Todo'lar başarıyla listelendi
          schema:
            items:
              $ref: '#/definitions/todos.Todo'
            type: array
        "500":
          description: Todo'lar listelenemedi
          schema:
            type: string
      summary: Get all Todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Bu endpoint, yeni bir todo eklemek için kullanılır.
      parameters:
      - description: Todo nesnesi
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/todos.Todo'
      produces:
      - application/json
      responses:
        "201":
          description: Todo başarıyla eklendi
          schema:
            type: string
        "400":
          description: Geçersiz veri
          schema:
            type: string
        "500":
          description: Todo eklenemedi
          schema:
            type: string
      summary: Create a new Todo
      tags:
      - todos
  /todos/{id}:
    delete:
      description: Bu endpoint, belirli bir todo'yu siler.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Todo başarıyla silindi
          schema:
            type: string
        "500":
          description: Todo silinemedi
          schema:
            type: string
      summary: Delete a Todo
      tags:
      - todos
    get:
      description: Bu endpoint, belirli bir todo'yu getirir.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Belirli todo başarıyla getirildi
          schema:
            $ref: '#/definitions/todos.Todo'
        "404":
          description: Todo bulunamadı
          schema:
            type: string
        "500":
          description: Veritabanı hatası
          schema:
            type: string
      summary: Get a Todo by ID
      tags:
      - todos
    put:
      consumes:
      - application/json
      description: Bu endpoint, belirli bir todo'yu günceller.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Todo nesnesi
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/todos.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: Todo başarıyla güncellendi
          schema:
            type: string
        "400":
          description: Geçersiz veri
          schema:
            type: string
        "500":
          description: Todo güncellenemedi
          schema:
            type: string
      summary: Update a Todo
      tags:
      - todos
swagger: "2.0"
